In [1]:
!pip install numpy pandas

In [2]:
import numpy as np

numpy -- это библиотека для научных вычислений

Написана на (кроме Python) C, немножко Fortran. А что это значит? Значит, что супер-пупер быстрая :)

И еще немножко фич с описания на оф. сайте:
* a powerful N-dimensional array object
* sophisticated (broadcasting) functions
* tools for integrating C/C++ and Fortran code
* useful linear algebra, Fourier transform, and random number capabilities

Классно то, что массивы типизированы! Про это на лекции еще поговорим.

Один из способов создать массив:

In [3]:
a = np.array([1, 2, 3], dtype=np.int16)
print(type(a))
print(a.shape)

<class 'numpy.ndarray'>
(3,)


In [4]:
a

array([1, 2, 3], dtype=int16)

### Задание: создайте двумерный массив (заполните чем угодно) с np.float32

In [7]:
# TODO
# your code hear
b = np.array([[3,4,5],[6,7,8]], dtype=np.float32)
b

array([[3., 4., 5.],
       [6., 7., 8.]], dtype=float32)

Есть классное индексирование:

In [8]:
a = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int16)
print(a)

[[1 2 3]
 [4 5 6]]


Тут, думаю, понятно:

In [9]:
a[0]

array([1, 2, 3], dtype=int16)

Тут тоже:

In [10]:
a[1, 0]

4

Можно делать слайсы по осям. Получим 2-ой столбец матрицы:

In [11]:
a[:, 1]

array([2, 5], dtype=int16)

### Задание: выведите
* 3-ий столбец
* все элементы, кроме последнего, из предпоследнего столбца
* (*) а теперь каждый 2-ой элемент (начиная с 0-ого индекса) последней строчки массива `b`

Конечно же, без всяких `for`, используем слайсы.

In [20]:
# создадим массив и заполним его рандомными элементами
# numpy умеет такое из коробки, используем np.random
b = np.random.randint(low=0, high=100, size=(20, 10))
print(b[:,2])
print(b[:19, 9])
print(b[19,::2])
# TODO
# your code hear

[98 57 42 90 85 28 61 42 66 85 54 47 21 41 81  5 60 14 33 20]
[70 79 92 69 27 10  9 73 88 45 90 69 54 40 21 38 84 19 37]
[27 20 80 17 70]


### Задание "на погуглить": выведите все четные элементы массива `c` (используя слайсы (да, и так тут можно))

In [104]:
c = np.random.randint(low=0, high=100, size=100)

In [105]:
# TODO
# your code hear
print(c)
print(c[::2])

[75 92 38 97 70 90 73 76 86 89 22 19 24  2 79 52 24 49 98  7 56 56 29 61
 68 68 22 74 81  1  9 90  2 70 59 14  6 10 62 34 65 60 72 31 96 12 30 41
 84 80 42 24 75 71 25 42 78 41 14  8 28 32 18 64 12 13 57 19 96 83 32 97
 26 80 13 91 26 32 84  6 87  8 50 50 95 51 88 37 97 40 27  9 51 28 20 74
 99 76 34 27]
[75 38 70 73 86 22 24 79 24 98 56 29 68 22 81  9  2 59  6 62 65 72 96 30
 84 42 75 25 78 14 28 18 12 57 96 32 26 13 26 84 87 50 95 88 97 27 51 20
 99 34]


Немного посмотрим на операции с `np.array`:

In [28]:
a = np.random.randint(low=0, high=100, size=(3, 4))
b = np.random.randint(low=0, high=100, size=(3, 4))
c = np.random.randint(low=0, high=100, size=4)
d = 42

print(f"a: {a}", end="\n\n")
print(f"b: {b}", end="\n\n")
print(f"c: {c}", end="\n\n")

a: [[12  6  8 78]
 [29 37 51 31]
 [27 41  4 35]]

b: [[57 86 54  7]
 [61 69 97 44]
 [66 22 92 83]]

c: [25 81 90 88]



In [29]:
a + b

array([[ 69,  92,  62,  85],
       [ 90, 106, 148,  75],
       [ 93,  63,  96, 118]])

In [30]:
a - b

array([[-45, -80, -46,  71],
       [-32, -32, -46, -13],
       [-39,  19, -88, -48]])

In [31]:
b.T

array([[57, 61, 66],
       [86, 69, 22],
       [54, 97, 92],
       [ 7, 44, 83]])

Какое это умножение?

In [32]:
a * b

array([[ 684,  516,  432,  546],
       [1769, 2553, 4947, 1364],
       [1782,  902,  368, 2905]])

А это?

In [33]:
a @ b.T

array([[ 2178,  5354,  8134],
       [ 7806, 10633,  9993],
       [ 5526,  6404,  5957]])

In [34]:
a / b

array([[ 0.21052632,  0.06976744,  0.14814815, 11.14285714],
       [ 0.47540984,  0.53623188,  0.5257732 ,  0.70454545],
       [ 0.40909091,  1.86363636,  0.04347826,  0.42168675]])

In [35]:
a = np.array([[5, 4], [7, 8]])
for_pow = np.array([2, 3])

a ** for_pow

array([[ 25,  64],
       [ 49, 512]], dtype=int32)

In [36]:
np.sqrt(b)

array([[7.54983444, 9.2736185 , 7.34846923, 2.64575131],
       [7.81024968, 8.30662386, 9.8488578 , 6.63324958],
       [8.1240384 , 4.69041576, 9.59166305, 9.11043358]])

In [37]:
np.sum(b)

738

In [38]:
np.min(a[0])

4

А эта штука называется broadcasting. Можно почитать [тут](http://cs231n.github.io/python-numpy-tutorial/#numpy-broadcasting), а вообще на лекции расскажем.

In [39]:
a + c

ValueError: operands could not be broadcast together with shapes (2,2) (4,) 

In [40]:
b - d

array([[ 15,  44,  12, -35],
       [ 19,  27,  55,   2],
       [ 24, -20,  50,  41]])

### Задание (*): с помощью `np.random.randint` создайте два массива (`x` и `y`) с элементами в диапазоне [-1000, 1000], размерами (12, 42) и (42, 12), соответственно. Найдите самое большое положительное нечетное число последнего столбца произведения матриц `x` и `y`.

In [102]:
# TODO
# your code hear
x = np.random.randint(low=-1000, high=1000, size=(12, 42))
y = np.random.randint(low=-1000, high=1000, size=(42, 12))
xy = x @ y
xylist = xy[:,11]

print(xylist)
xylist=xylist[xylist%2==1]
print(xylist)
xylist=xylist[xylist>0]
print(xylist)
print(np.max(xylist))

[ -931938  -880664 -1832818  -631946  -588288  2611280  2473870  1770615
 -1363637 -2212558  2829323  1776506]
[ 1770615 -1363637  2829323]
[1770615 2829323]
2829323


# PANDAAAAAS

In [45]:
import pandas as pd

Pandas — программная библиотека на языке Python для обработки и анализа данных. Работа pandas с данными строится поверх библиотеки NumPy.

Мы сейчас рассмотрим следующее: 
    - посмотрим два объекта из библиотеки pandas: Series и DataFrame.
    - пощупаем что это вообще такое.

In [46]:
Series - объект похожий на list в питоне, он упорядочен и туда можно положить что угодно)
Однако на деле объект Series больше похож на упорядоченный словарь OrderedDict, 
тк у Series помимо значений есть еще и индексы.

SyntaxError: invalid syntax (<ipython-input-46-1428ced06d46>, line 1)

In [47]:
a = pd.Series(data=['амир', 'миша', 'илья', 'зарина', 'игорь'])

In [48]:
# в строковом представлении в столбце слева - индексы, справа - значения.
a

0      амир
1      миша
2      илья
3    зарина
4     игорь
dtype: object

In [49]:
# мы можем создавать серии со своей индексацией

a = pd.Series(data=['амир', 'миша', 'илья', 'зарина', 'игорь'], 
              index=[101,102,103,104,105])

In [50]:
# и обращаться по индексу

a[103]

'илья'

In [51]:
# внутри все хранится в виде np.array

a.values

array(['амир', 'миша', 'илья', 'зарина', 'игорь'], dtype=object)

In [52]:
a.index

Int64Index([101, 102, 103, 104, 105], dtype='int64')

In [53]:
# мы можем создать Series вот так:

a = pd.Series({'a': 1, 'b': 2, 'c': 3, 'd': 4})

In [54]:
a

a    1
b    2
c    3
d    4
dtype: int64

In [55]:
# мы можем на лету поменять индекс

a.index=[1,2,3,4]

In [56]:
a

1    1
2    2
3    3
4    4
dtype: int64

In [57]:
# у Series есть поле name и его мы можем изменять

a.name='fofoofof'

In [58]:
a

1    1
2    2
3    3
4    4
Name: fofoofof, dtype: int64

___________

DataFrame в простом случае это таблица. 

у нее есть строки и столбцы.

столбцами в DataFrame являются объекты Series.

у DataFrame есть индекс по строкам, который по умолчанию задается в числовом диапазоне начниая с 0.

Индексом по столбцам является название колонок.

In [59]:
d = {'колонка_1': [1, 2, 3, 4, 5], 
     'колонка_2': ['амир', 'миша', 'илья', 'зарина', 'игорь'], 
     'колонка_возраст':['засекречено','засекречено','засекречено','засекречено','засекречено']}
df = pd.DataFrame(data=d)

In [60]:
df

колонка_1 колонка_2 колонка_возраст
0          1      амир     засекречено
1          2      миша     засекречено
2          3      илья     засекречено
3          4    зарина     засекречено
4          5     игорь     засекречено

основные способы создать DataFrame внизу - но мы с вами еще об этом поговорим на лекци

![](https://pbpython.com/images/pandas-dataframe-shadow.png)

In [61]:
# пандас умеет загружать данные из разных источников
# разберем это на лекции, а пока давайте поиграемся с большим датафреймом.
# ниже пример загрузки из .tsv файла. 

titanik_csv = pd.read_csv('titanic.tsv', sep='|', index_col=0)

# 1. посмотреть как выглядят данные

In [62]:
# вывести первые n элементов (по умолчанию n=5)

titanik_csv.head()

pclass  survived                                             name     sex  \
0       1         1                    Allen, Miss. Elisabeth Walton  female   
1       1         1                   Allison, Master. Hudson Trevor    male   
2       1         0                     Allison, Miss. Helen Loraine  female   
3       1         0             Allison, Mr. Hudson Joshua Creighton    male   
4       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female   

       age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
0  29.0000      0      0   24160  211.3375       B5        S    2    NaN   
1   0.9167      1      2  113781  151.5500  C22 C26        S   11    NaN   
2   2.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
3  30.0000      1      2  113781  151.5500  C22 C26        S  NaN  135.0   
4  25.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   

                         home.dest  
0                     St Louis, MO  
1  Montreal, PQ / Chesterville, ON  
2  Montreal, PQ / Chesterville, ON  
3  Montreal, PQ / Chesterville, ON  
4  Montreal, PQ / Chesterville, ON

In [63]:
# вывести 10 последних элементов (по умолчанию 5)

titanik_csv.tail(n=10)

pclass  survived                                     name     sex   age  \
1299       3         0                      Yasbeck, Mr. Antoni    male  27.0   
1300       3         1  Yasbeck, Mrs. Antoni (Selini Alexander)  female  15.0   
1301       3         0                     Youseff, Mr. Gerious    male  45.5   
1302       3         0                        Yousif, Mr. Wazli    male   NaN   
1303       3         0                    Yousseff, Mr. Gerious    male   NaN   
1304       3         0                     Zabour, Miss. Hileni  female  14.5   
1305       3         0                    Zabour, Miss. Thamine  female   NaN   
1306       3         0                Zakarian, Mr. Mapriededer    male  26.5   
1307       3         0                      Zakarian, Mr. Ortin    male  27.0   
1308       3         0                       Zimmerman, Mr. Leo    male  29.0   

      sibsp  parch  ticket     fare cabin embarked boat   body home.dest  
1299      1      0    2659  14.4542   NaN        C    C    NaN       NaN  
1300      1      0    2659  14.4542   NaN        C  NaN    NaN       NaN  
1301      0      0    2628   7.2250   NaN        C  NaN  312.0       NaN  
1302      0      0    2647   7.2250   NaN        C  NaN    NaN       NaN  
1303      0      0    2627  14.4583   NaN        C  NaN    NaN       NaN  
1304      1      0    2665  14.4542   NaN        C  NaN  328.0       NaN  
1305      1      0    2665  14.4542   NaN        C  NaN    NaN       NaN  
1306      0      0    2656   7.2250   NaN        C  NaN  304.0       NaN  
1307      0      0    2670   7.2250   NaN        C  NaN    NaN       NaN  
1308      0      0  315082   7.8750   NaN        S  NaN    NaN       NaN

In [64]:
# вывести 10 случайных элементов (по умолчанию 5)

titanik_csv.sample(n=10)

pclass  survived                                           name     sex  \
367        2         0                     Chapman, Mr. Charles Henry    male   
429        2         0                         Harbeck, Mr. William H    male   
586        2         1  Weisz, Mrs. Leopold (Mathilde Francoise Pede)  female   
255        1         1                           Sagesser, Mlle. Emma  female   
673        3         0                            Betros, Mr. Tannous    male   
257        1         1                Schabert, Mrs. Paul (Emma Mock)  female   
406        2         0                          Faunthorpe, Mr. Harry    male   
797        3         0                             Farrell, Mr. James    male   
487        2         0                              Lingane, Mr. John    male   
1238       3         1                     Tenglin, Mr. Gunnar Isidor    male   

       age  sibsp  parch    ticket     fare cabin embarked   boat   body  \
367   52.0      0      0    248731  13.5000   NaN        S    NaN  130.0   
429   44.0      0      0    248746  13.0000   NaN        S    NaN   35.0   
586   29.0      1      0    228414  26.0000   NaN        S     10    NaN   
255   24.0      0      0  PC 17477  69.3000   B35        C      9    NaN   
673   20.0      0      0      2648   4.0125   NaN        C    NaN    NaN   
257   35.0      1      0     13236  57.7500   C28        C     11    NaN   
406   40.0      1      0      2926  26.0000   NaN        S    NaN  286.0   
797   40.5      0      0    367232   7.7500   NaN        Q    NaN   68.0   
487   61.0      0      0    235509  12.3500   NaN        Q    NaN    NaN   
1238  25.0      0      0    350033   7.7958   NaN        S  13 15    NaN   

                                           home.dest  
367                                        Bronx, NY  
429                         Seattle, WA / Toledo, OH  
586               Bromsgrove, England / Montreal, PQ  
255                                              NaN  
673                                            Syria  
257                                     New York, NY  
406                       England / Philadelphia, PA  
797   Aughnacliff, Co Longford, Ireland New York, NY  
487                                              NaN  
1238                                             NaN

In [65]:
# тк pandas сделан на основе numpy, то мы можем так же стандартно посмотреть размерность таблички через
# свойство shape

titanik_csv.shape

(1309, 14)

>  мы видим что у нас 1309 строк и 14 колонок

In [66]:
# мы в силах посмотреть всю табличку целиком.

titanik_csv

pclass  survived                                               name  \
0          1         1                      Allen, Miss. Elisabeth Walton   
1          1         1                     Allison, Master. Hudson Trevor   
2          1         0                       Allison, Miss. Helen Loraine   
3          1         0               Allison, Mr. Hudson Joshua Creighton   
4          1         0    Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
5          1         1                                Anderson, Mr. Harry   
6          1         1                  Andrews, Miss. Kornelia Theodosia   
7          1         0                             Andrews, Mr. Thomas Jr   
8          1         1      Appleton, Mrs. Edward Dale (Charlotte Lamson)   
9          1         0                            Artagaveytia, Mr. Ramon   
10         1         0                             Astor, Col. John Jacob   
11         1         1  Astor, Mrs. John Jacob (Madeleine Talmadge Force)   
12         1         1                      Aubart, Mme. Leontine Pauline   
13         1         1                       Barber, Miss. Ellen "Nellie"   
14         1         1               Barkworth, Mr. Algernon Henry Wilson   
15         1         0                                Baumann, Mr. John D   
16         1         0                           Baxter, Mr. Quigg Edmond   
17         1         1    Baxter, Mrs. James (Helene DeLaudeniere Chaput)   
18         1         1                              Bazzani, Miss. Albina   
19         1         0                               Beattie, Mr. Thomson   
20         1         1                      Beckwith, Mr. Richard Leonard   
21         1         1   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)   
22         1         1                              Behr, Mr. Karl Howell   
23         1         1                              Bidois, Miss. Rosalie   
24         1         1                                  Bird, Miss. Ellen   
25         1         0                                Birnbaum, Mr. Jakob   
26         1         1                            Bishop, Mr. Dickinson H   
27         1         1            Bishop, Mrs. Dickinson H (Helen Walton)   
28         1         1                             Bissette, Miss. Amelia   
29         1         1          Bjornstrom-Steffansson, Mr. Mauritz Hakan   
...      ...       ...                                                ...   
1279       3         0               Vestrom, Miss. Hulda Amanda Adolfina   
1280       3         0                                    Vovk, Mr. Janko   
1281       3         0                               Waelens, Mr. Achille   
1282       3         0                                Ware, Mr. Frederick   
1283       3         0                        Warren, Mr. Charles William   
1284       3         0                                  Webber, Mr. James   
1285       3         0                                Wenzel, Mr. Linhart   
1286       3         1    Whabee, Mrs. George Joseph (Shawneene Abi-Saab)   
1287       3         0                   Widegren, Mr. Carl/Charles Peter   
1288       3         0                          Wiklund, Mr. Jakob Alfred   
1289       3         0                            Wiklund, Mr. Karl Johan   
1290       3         1                   Wilkes, Mrs. James (Ellen Needs)   
1291       3         0                   Willer, Mr. Aaron ("Abi Weller")   
1292       3         0                                 Willey, Mr. Edward   
1293       3         0                  Williams, Mr. Howard Hugh "Harry"   
1294       3         0                               Williams, Mr. Leslie   
1295       3         0                                Windelov, Mr. Einar   
1296       3         0                                   Wirz, Mr. Albert   
1297       3         0                             Wiseman, Mr. Phillippe   
1298       3         0                          Wittevrongel, Mr. Camille   
12

вы конечно можете посмотреть почти всю табличку целиком, вас ограничивают настройки отображения табличек в пандасе.

> это поля 

> pd.options.display.max_columns - максимальное число колонок которое будет отрисовано

> pd.options.display.max_rows - максимальное число строк которое будет отрисовано

конечно же как программисты мы можем все это поменять.

In [67]:
pd.options.display.max_columns = 5

In [68]:
pd.options.display.max_rows = 20

In [69]:
# стало хуже?

titanik_csv

pclass  survived               ...                  body  \
0          1         1               ...                   NaN   
1          1         1               ...                   NaN   
2          1         0               ...                   NaN   
3          1         0               ...                 135.0   
4          1         0               ...                   NaN   
5          1         1               ...                   NaN   
6          1         1               ...                   NaN   
7          1         0               ...                   NaN   
8          1         1               ...                   NaN   
9          1         0               ...                  22.0   
...      ...       ...               ...                   ...   
1299       3         0               ...                   NaN   
1300       3         1               ...                   NaN   
1301       3         0               ...                 312.0   
1302       3         0               ...                   NaN   
1303       3         0               ...                   NaN   
1304       3         0               ...                 328.0   
1305       3         0               ...                   NaN   
1306       3         0               ...                 304.0   
1307       3         0               ...                   NaN   
1308       3         0               ...                   NaN   

                            home.dest  
0                        St Louis, MO  
1     Montreal, PQ / Chesterville, ON  
2     Montreal, PQ / Chesterville, ON  
3     Montreal, PQ / Chesterville, ON  
4     Montreal, PQ / Chesterville, ON  
5                        New York, NY  
6                          Hudson, NY  
7                         Belfast, NI  
8                 Bayside, Queens, NY  
9                 Montevideo, Uruguay  
...                               ...  
1299                              NaN  
1300                              NaN  
1301                              NaN  
1302                              NaN  
1303                              NaN  
1304                              NaN  
1305                              NaN  
1306                              NaN  
1307                              NaN  
1308                              NaN  

[1309 rows x 14 columns]

In [70]:
# поставим чтоб было удобнее
pd.options.display.max_columns = 20
pd.options.display.max_rows = 200 # рекомендую ставить большое значение только если у вас мощный комп)

# 2. начнем смотреть столбцы ближе.

Для того чтобы понять какой столбец (признак) что означает почитайте об этом в разделе Data
https://www.kaggle.com/c/titanic/data . 

Пока вы не запомните, может быть полезно выписать название всех столбцов и что они значат прямо в нотбук - сюда:

* Survived - Выжил или нет
* Pclass - 1, 2 или 3 класс билета 
* Name - имя
* Sex - пол
* Age - возраст в годах
* SibSp - сестер/братьев/супругов на борту
* Parch - детей/родителей на борту
* Ticket - номер билета
* Fare - услуги???
* Cabin - номер каюты
* Embarked - Порт погрузки C = Cherbourg, Q = Queenstown, S = Southampton

несколько полезных методов которые помогут быстро посмотреть общие характеристики данных:

1. .describe() - Выведет количество, среднее, стандартное отклонение, квантили, минимум и максимум всех **числовых признаков** (столбцов)
2. .columns - это поле а не метод (в конце скобки не надо писать). Выведет название всех колонок.
3. .count() - выведет количесто **не пропущенных** значений в каждом столбце (not nan значений)
4. .nunique() - выведет количество уникальных значений в каждом столбце
5. .dtypes - это поле а не метод (в конце скобки не надо писать). Выведет тип переменной хранящейся в каждом столбце


In [71]:
titanik_csv.describe()

pclass     survived          age        sibsp        parch  \
count  1309.000000  1309.000000  1046.000000  1309.000000  1309.000000   
mean      2.294882     0.381971    29.881135     0.498854     0.385027   
std       0.837836     0.486055    14.413500     1.041658     0.865560   
min       1.000000     0.000000     0.166700     0.000000     0.000000   
25%       2.000000     0.000000    21.000000     0.000000     0.000000   
50%       3.000000     0.000000    28.000000     0.000000     0.000000   
75%       3.000000     1.000000    39.000000     1.000000     0.000000   
max       3.000000     1.000000    80.000000     8.000000     9.000000   

              fare        body  
count  1308.000000  121.000000  
mean     33.295479  160.809917  
std      51.758668   97.696922  
min       0.000000    1.000000  
25%       7.895800   72.000000  
50%      14.454200  155.000000  
75%      31.275000  256.000000  
max     512.329200  328.000000

In [72]:
titanik_csv.count()

pclass       1309
survived     1309
name         1309
sex          1309
age          1046
sibsp        1309
parch        1309
ticket       1309
fare         1308
cabin         295
embarked     1307
boat          486
body          121
home.dest     745
dtype: int64

In [73]:
titanik_csv.nunique()

pclass          3
survived        2
name         1307
sex             2
age            98
sibsp           7
parch           8
ticket        929
fare          281
cabin         186
embarked        3
boat           27
body          121
home.dest     369
dtype: int64

In [74]:
# там где строки пандас по умолчанию пишет object
# иногда полезно посмотреть что тут.

titanik_csv.dtypes

pclass         int64
survived       int64
name          object
sex           object
age          float64
sibsp          int64
parch          int64
ticket        object
fare         float64
cabin         object
embarked      object
boat          object
body         float64
home.dest     object
dtype: object

мы можем напрямую обращаться к столбцу, столбцам, строке и строкам.

https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html

In [75]:
# самый простой способ обратиться к столбцу - это написать его название через точку
# давайте обратимся к полю sex
# нам вернется pd.Series - прямо вся колонка


titanik_csv.sex

0       female
1         male
2       female
3         male
4       female
5         male
6       female
7         male
8       female
9         male
10        male
11      female
12      female
13      female
14        male
15        male
16        male
17      female
18      female
19        male
20        male
21      female
22        male
23      female
24      female
25        male
26        male
27      female
28      female
29        male
30        male
31        male
32      female
33      female
34        male
35      female
36      female
37        male
38        male
39        male
40        male
41      female
42      female
43      female
44      female
45        male
46        male
47        male
48      female
49        male
50      female
51        male
52        male
53        male
54        male
55      female
56        male
57      female
58        male
59      female
60        male
61      female
62        male
63      female
64        male
65      female
66      fe

In [76]:
# еще можно обратиться через квадратные скобки
# эффект будет совершенно таким же

titanik_csv["sex"]

0       female
1         male
2       female
3         male
4       female
5         male
6       female
7         male
8       female
9         male
10        male
11      female
12      female
13      female
14        male
15        male
16        male
17      female
18      female
19        male
20        male
21      female
22        male
23      female
24      female
25        male
26        male
27      female
28      female
29        male
30        male
31        male
32      female
33      female
34        male
35      female
36      female
37        male
38        male
39        male
40        male
41      female
42      female
43      female
44      female
45        male
46        male
47        male
48      female
49        male
50      female
51        male
52        male
53        male
54        male
55      female
56        male
57      female
58        male
59      female
60        male
61      female
62        male
63      female
64        male
65      female
66      fe

In [77]:
# через values мы можем получить np.array который хранится в вернувшемся объекте pd.Series

titanik_csv.sex.values

array(['female', 'male', 'female', ..., 'male', 'male', 'male'],
      dtype=object)

In [78]:
# силами pandas мы можем посмотреть различные значения содержащиеся в объекте pd.Series
# https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.value_counts.html
# обратите внимание на доп параметры этой функции

titanik_csv.sex.value_counts()

male      843
female    466
Name: sex, dtype: int64

# ТУДУШЕЧКА

> Вопрос Кого больше мужчин или женщин?

> ответ: мужчин

> Вопрос - объект какого типа возвращается после вызова  функции value_counts() ?

> ответ: series


в пандасе мы можем получить срез сразу по нескольким колонкам, тогда вернется новый DataFrame а не Series

In [79]:
titanik_csv[ ['sex', 'age'] ]

sex      age
0     female  29.0000
1       male   0.9167
2     female   2.0000
3       male  30.0000
4     female  25.0000
5       male  48.0000
6     female  63.0000
7       male  39.0000
8     female  53.0000
9       male  71.0000
10      male  47.0000
11    female  18.0000
12    female  24.0000
13    female  26.0000
14      male  80.0000
15      male      NaN
16      male  24.0000
17    female  50.0000
18    female  32.0000
19      male  36.0000
20      male  37.0000
21    female  47.0000
22      male  26.0000
23    female  42.0000
24    female  29.0000
25      male  25.0000
26      male  25.0000
27    female  19.0000
28    female  35.0000
29      male  28.0000
30      male  45.0000
31      male  40.0000
32    female  30.0000
33    female  58.0000
34      male  42.0000
35    female  45.0000
36    female  22.0000
37      male      NaN
38      male  41.0000
39      male  48.0000
40      male      NaN
41    female  44.0000
42    female  59.0000
43    female  60.0000
44    female  41.0000
45      male  45.0000
46      male      NaN
47      male  42.0000
48    female  53.0000
49      male  36.0000
50    female  58.0000
51      male  33.0000
52      male  28.0000
53      male  17.0000
54      male  11.0000
55    female  14.0000
56      male  36.0000
57    female  36.0000
58      male  49.0000
59    female      NaN
60      male  36.0000
61    female  76.0000
62      male  46.0000
63    female  47.0000
64      male  27.0000
65    female  33.0000
66    female  36.0000
67    female  30.0000
68      male  45.0000
69    female      NaN
70      male      NaN
71      male  27.0000
72    female  26.0000
73    female  22.0000
74      male      NaN
75      male  47.0000
76    female  39.0000
77      male  37.0000
78    female  64.0000
79    female  55.0000
80      male      NaN
81      male  70.0000
82    female  36.0000
83    female  64.0000
84      male  39.0000
85    female  38.0000
86      male  51.0000
87      male  27.0000
88    female  33.0000
89      male  31.0000
90    female  27.0000
91      male  31.0000
92    female  17.0000
93      male  53.0000
94      male   4.0000
95    female  54.0000
96      male  50.0000
97    female  27.0000
98    female  48.0000
99    female  48.0000
...      ...      ...
1209  female   2.0000
1210    male  40.0000
1211  female  45.0000
1212    male      NaN
1213    male      NaN
1214    male      NaN
1215    male      NaN
1216  female      NaN
1217    male  19.0000
1218    male  30.0000
1219    male      NaN
1220    male  32.0000
1221    male      NaN
1222    male  33.0000
1223  female  23.0000
1224    male  21.0000
1225    male  60.5000
1226    male  19.0000
1227  female  22.0000
1228    male  31.0000
1229    male  27.0000
1230  female   2.0000
1231  female  29.0000
1232    male  16.0000
1233    male  44.0000
1234    male  25.0000
1235    male  74.0000
1236    male  14.0000
1237    male  24.0000
1238    male  25.0000
1239    male  34.0000
1240    male   0.4167
1241    male      NaN
1242    male      NaN
1243    male      NaN
1244  female  16.0000
1245    male      NaN
1246    male      NaN
1247  female      NaN
1248    male  32.0000
1249    male      NaN
1250    male      NaN
1251    male  30.5000
1252    male  44.0000
1253    male      NaN
1254    male  25.0000
1255    male      NaN
1256    male   7.0000
1257  female   9.0000
1258  female  29.0000
1259    male  36.0000
1260  female  18.0000
1261  female  63.0000
1262    male      NaN
1263    male  11.5000
1264    male  40.5000
1265  female  10.0000
1266    male  36.0000
1267  female  30.0000
1268    male      NaN
1269    male  33.0000
1270    male  28.0000
1271    male  28.0000
1272    male  47.0000
1273  female  18.0000
1274    male  31.0000
1275    male  16.0000
1276  female  31.0000
1277    male  22.0000
1278    male  20.0000
1279  female  14.0000
1280    male  22.0000
1281    male  22.0000
1282    male      NaN
1283    male      NaN
1284    male      NaN
1285    male  32.5000
1286  female  38.0000
1287    male  51.0000
1288    male  18.0000
1289 

Самый каноничный способ обращения к полям - через loc или iloc

loc - позволяет обратиться по названию индексов, 

iloc - по нумерованному значению (то есть обращаемся через цифры, начиная с нуля)

In [80]:
titanik_csv.loc[:, 'sex']

0       female
1         male
2       female
3         male
4       female
5         male
6       female
7         male
8       female
9         male
10        male
11      female
12      female
13      female
14        male
15        male
16        male
17      female
18      female
19        male
20        male
21      female
22        male
23      female
24      female
25        male
26        male
27      female
28      female
29        male
30        male
31        male
32      female
33      female
34        male
35      female
36      female
37        male
38        male
39        male
40        male
41      female
42      female
43      female
44      female
45        male
46        male
47        male
48      female
49        male
50      female
51        male
52        male
53        male
54        male
55      female
56        male
57      female
58        male
59      female
60        male
61      female
62        male
63      female
64        male
65      female
66      fe

чтобы в дальнейшем экономить место - будем смотреть только первые 5 записей

In [81]:
titanik_csv.loc[:, 'sex'].head()

0    female
1      male
2    female
3      male
4    female
Name: sex, dtype: object

In [82]:
titanik_csv.loc[:, ['sex', 'age']].head()

sex      age
0  female  29.0000
1    male   0.9167
2  female   2.0000
3    male  30.0000
4  female  25.0000

In [83]:
titanik_csv.loc[[12,13,14,17,17], ['sex', 'age']].head()

sex   age
12  female  24.0
13  female  26.0
14    male  80.0
17  female  50.0
17  female  50.0

In [84]:
titanik_csv.iloc[[12,13,14,17,17], [3, 4]].head()

sex   age
12  female  24.0
13  female  26.0
14    male  80.0
17  female  50.0
17  female  50.0

# 3. мы можем работать с полями и изменять их как хотим.

In [85]:
titanik_csv.loc[0, 'name']

'Allen, Miss. Elisabeth Walton'

например, давайте выделим только первую часть имени.

как мы это делаем с одной строкой?

In [86]:
titanik_csv.loc[0, 'name'].split(',')[0]

'Allen'

чтобы проделать этот финт со всеми строками - не нужно итерироваться в цикле.

достаточно применить некоторую функцию ко всем строкам через метод apply

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.apply.html

In [87]:
titanik_csv['name'].head().apply(lambda x: x.split(',')[0])

0      Allen
1    Allison
2    Allison
3    Allison
4    Allison
Name: name, dtype: object

на основе этого мы можем создать новую колонку.

In [88]:
titanik_csv['only_name'] = titanik_csv['name'].apply(lambda x: x.split(',')[0])

In [89]:
titanik_csv.head()

pclass  survived                                             name     sex  \
0       1         1                    Allen, Miss. Elisabeth Walton  female   
1       1         1                   Allison, Master. Hudson Trevor    male   
2       1         0                     Allison, Miss. Helen Loraine  female   
3       1         0             Allison, Mr. Hudson Joshua Creighton    male   
4       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female   

       age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
0  29.0000      0      0   24160  211.3375       B5        S    2    NaN   
1   0.9167      1      2  113781  151.5500  C22 C26        S   11    NaN   
2   2.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
3  30.0000      1      2  113781  151.5500  C22 C26        S  NaN  135.0   
4  25.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   

                         home.dest only_name  
0                     St Louis, MO     Allen  
1  Montreal, PQ / Chesterville, ON   Allison  
2  Montreal, PQ / Chesterville, ON   Allison  
3  Montreal, PQ / Chesterville, ON   Allison  
4  Montreal, PQ / Chesterville, ON   Allison

Отлично, мы немного пощупали, Pandas, и продолжим изучать его подробнее на лекции.