# `numpy`

In [1]:
import numpy as np

## Как создать массив в `numpy`?

In [11]:
a = np.array(["1", 2, "汉"])
b = np.array([1, 2, 3], dtype=np.uint16)
c = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]], dtype=np.float128)

AttributeError: module 'numpy' has no attribute 'float128'

In [12]:
a

array(['1', '2', '汉'], dtype='<U1')

In [13]:
b

array([1, 2, 3], dtype=uint16)

In [14]:
c

NameError: name 'c' is not defined

In [15]:
print(c.shape)

NameError: name 'c' is not defined

In [16]:
print(c.dtype)

NameError: name 'c' is not defined

### Чтобы не писать велосипеды для создания кастомных массивов есть:

In [17]:
np.zeros((2, 2)) # array of all zeroes

array([[0., 0.],
       [0., 0.]])

In [18]:
np.ones((1,2)) # array of all ones

array([[1., 1.]])

In [19]:
np.full((2,2), 42) # constant array

array([[42, 42],
       [42, 42]])

In [20]:
np.eye(3) # diagonal matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.random.randint(-10, 10, (2, 5)) # array of random elems

array([[-7, -3, -1,  6,  0],
       [ 5, -8, -9,  5,  0]])

## Индексирование и слайсы

In [22]:
a = np.random.randint(0, 100, size=(5, 10))
print(a)

[[83 21 33 86 54 95 34  2 48 34]
 [ 3 53 85 82 84 95 75 53 21 41]
 [66 67 43 45 97 45 14 36 15  9]
 [ 6  4 48 95 19 45 71 24 44 97]
 [10 76 81 44 22 62 53  2 49 35]]


In [23]:
a[0]

array([83, 21, 33, 86, 54, 95, 34,  2, 48, 34])

In [24]:
a[0, 1] # the same as a[0][1]

21

In [25]:
# Можно делать слайсы по осям. Получим 2-ой столбец матрицы:
a[:, 1]

array([21, 53, 67,  4, 76])

In [26]:
# выведем все элементы, кроме последнего, из предпоследнего столбца:
a[:-1, -2]

array([48, 21, 15, 44])

In [27]:
# а теперь каждый 2-ой элемент (начиная с 0-ого индекса) последней строчки:
a[-1, ::2]

array([10, 81, 22, 53, 49])

In [28]:
# каждый 2-ой элемент (начиная с 1-ого индекса) последней строчки:
a[-1, 1::2]

array([76, 44, 62,  2, 35])

In [31]:
# все положительные элементы массива:
a[a > 0]

array([83, 21, 33, 86, 54, 95, 34,  2, 48, 34,  3, 53, 85, 82, 84, 95, 75,
       53, 21, 41, 66, 67, 43, 45, 97, 45, 14, 36, 15,  9,  6,  4, 48, 95,
       19, 45, 71, 24, 44, 97, 10, 76, 81, 44, 22, 62, 53,  2, 49, 35])

In [32]:
# 1-ая и 5-ая строчки массива:
a[np.array([0, 4])]

array([[83, 21, 33, 86, 54, 95, 34,  2, 48, 34],
       [10, 76, 81, 44, 22, 62, 53,  2, 49, 35]])

### Для присваивания тоже работает!

In [33]:
a

array([[83, 21, 33, 86, 54, 95, 34,  2, 48, 34],
       [ 3, 53, 85, 82, 84, 95, 75, 53, 21, 41],
       [66, 67, 43, 45, 97, 45, 14, 36, 15,  9],
       [ 6,  4, 48, 95, 19, 45, 71, 24, 44, 97],
       [10, 76, 81, 44, 22, 62, 53,  2, 49, 35]])

In [34]:
a[1:-1, :] = 1
a

array([[83, 21, 33, 86, 54, 95, 34,  2, 48, 34],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [10, 76, 81, 44, 22, 62, 53,  2, 49, 35]])

In [35]:
a[:, 1:3] = np.arange(2)
a

array([[83,  0,  1, 86, 54, 95, 34,  2, 48, 34],
       [ 1,  0,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  0,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  0,  1,  1,  1,  1,  1,  1,  1,  1],
       [10,  0,  1, 44, 22, 62, 53,  2, 49, 35]])

## Операции с `np.array`

In [56]:
a = np.random.randint(low=0, high=100, size=(3, 4))
b = np.random.randint(low=0, high=100, size=(3, 4))
c = np.random.randint(low=0, high=100, size=4)
d = 42
e = np.random.randint(low=0, high=100, size=(4, 3))

print(f"a: {a}", end="\n\n")
print(f"b: {b}", end="\n\n")
print(f"c: {c}", end="\n\n")

a: [[72 28 21 29]
 [16 55 75 77]
 [ 0 15 55 61]]

b: [[34 77 80 59]
 [46 66 50 92]
 [ 4 41 44 44]]

c: [75 18 60 17]



In [38]:
print(a.reshape((2, 6))) # the same as a.shape = (2, 6)

[[ 6 75 42 22 29 33]
 [38 48 96  8  1 58]]


In [57]:
a @ e

array([[8449, 8506, 2577],
       [9622, 8758, 3223],
       [4610, 4706, 1587]])

In [39]:
print(a.T)

[[ 6 29 96]
 [75 33  8]
 [42 38  1]
 [22 48 58]]


In [40]:
a + b

array([[102, 165,  90, 119],
       [ 32, 132,  80, 130],
       [181,  90,  92, 120]])

In [41]:
a - b

array([[-90, -15,  -6, -75],
       [ 26, -66,  -4, -34],
       [ 11, -74, -90,  -4]])

In [42]:
# какое это умножение?
a * b

array([[ 576, 6750, 2016, 2134],
       [  87, 3267, 1596, 3936],
       [8160,  656,   91, 3596]])

In [43]:
# а это?
a @ b.T

array([[11476, 11011, 11846],
       [12234,  8886, 11605],
       [15610,  5878, 12503]])

In [44]:
a / b

array([[0.0625    , 0.83333333, 0.875     , 0.22680412],
       [9.66666667, 0.33333333, 0.9047619 , 0.58536585],
       [1.12941176, 0.09756098, 0.01098901, 0.93548387]])

In [50]:
a = np.array([[5, 4], [7, 8]])
for_pow = np.array([2, 3])

a ** for_pow

array([[ 25,  64],
       [ 49, 512]], dtype=int32)

In [51]:
print(b)
np.sqrt(b)

[[96 90 48 97]
 [ 3 99 42 82]
 [85 82 91 62]]


array([[9.79795897, 9.48683298, 6.92820323, 9.8488578 ],
       [1.73205081, 9.94987437, 6.4807407 , 9.05538514],
       [9.21954446, 9.05538514, 9.53939201, 7.87400787]])

In [52]:
np.sum(b)

877

In [53]:
np.sum(b, axis=0)

array([184, 271, 181, 241])

In [54]:
np.min(a[0])

4

In [58]:
np.vstack([a, b])

array([[72, 28, 21, 29],
       [16, 55, 75, 77],
       [ 0, 15, 55, 61],
       [34, 77, 80, 59],
       [46, 66, 50, 92],
       [ 4, 41, 44, 44]])

In [59]:
np.hstack([a, b])

array([[72, 28, 21, 29, 34, 77, 80, 59],
       [16, 55, 75, 77, 46, 66, 50, 92],
       [ 0, 15, 55, 61,  4, 41, 44, 44]])

### Волшебный `np.vectorize`

In [60]:
pow_2 = lambda x: x ** 2

In [61]:
pow_2(np.array([2, 3, 4]))

array([ 4,  9, 16], dtype=int32)

In [62]:
pow_2([2, 3, 4])

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [63]:
pow_2_vec = np.vectorize(pow_2)
pow_2_vec([2, 3, 4])

array([ 4,  9, 16])

### Немного про broadcasting

In [65]:
a + d

array([[114,  70,  63,  71],
       [ 58,  97, 117, 119],
       [ 42,  57,  97, 103]])

In [68]:
t1 = np.array([[4],[5],[6],[7]])
t2 = np.array([1,0,1,0])

In [69]:
t1+t2

array([[5, 4, 5, 4],
       [6, 5, 6, 5],
       [7, 6, 7, 6],
       [8, 7, 8, 7]])

In [70]:
a + c

array([[147,  46,  81,  46],
       [ 91,  73, 135,  94],
       [ 75,  33, 115,  78]])

In [71]:
b - d

array([[ -8,  35,  38,  17],
       [  4,  24,   8,  50],
       [-38,  -1,   2,   2]])

#### Задание (*): с помощью `np.random.randint` создайте два массива (`x` и `y`) с элементами в диапазоне [-1000, 1000], размерами (12, 42) и (42, 12), соответственно. Найдите самое большое положительное нечетное число последнего столбца произведения матриц `x` и `y`.

In [72]:
x = np.random.randint(-1000, 1000, (12, 42))
y = np.random.randint(-1000, 1000, (42, 12))

tmp = (x @ y)[:, -1]
print(tmp[(tmp % 2 == 1) & (tmp > 0)].max())

3172919


### Задание: написать решалку линейных уравнений

In [84]:
# Линейные уравнения можно решать следующим образом: Ax = y, где A-матрица. 
# A^(T)Ax=A^(T)y
# x=(A^(T)A)^(-1)A^(T)y
# давайте сделаем свою решалку таких уравнений
# HINT: np.linalg...

def solution_finder(A, y):
    return np.linalg.solve(A,y)

### Задание: решить систему методом [Крамера](https://ru.wikipedia.org/wiki/%D0%9C%D0%B5%D1%82%D0%BE%D0%B4_%D0%9A%D1%80%D0%B0%D0%BC%D0%B5%D1%80%D0%B0)

In [85]:
#TODO решить систему методом Крамера
#HINT: np.linalg.det

def cramer_solver(A, b):
    res = np.array()
    d0 = np.linalg.det(A)
    for i in range(A.shape[0]):
        aa = copy.deepcopy(A)
        aa[:,i]=b
        res.append(np.linalg.det(aa)/d0)
    return res
    return np.array(map(lambda : x[,A[:,:] for i in range(A.shape[0])))

## Few more things:

### `np.random.seed()`

In [76]:
for i in range(5):
    arr = np.arange(5)  # [0, 1, 2, 3, 4]
    np.random.seed(1)  # Reset random state
    np.random.shuffle(arr)  # Shuffle!
    print(arr)

[2 1 4 0 3]
[2 1 4 0 3]
[2 1 4 0 3]
[2 1 4 0 3]
[2 1 4 0 3]


In [77]:
np.random.seed(3)
print(np.random.random())

np.random.seed(3)
print(np.random.random())

0.5507979025745755
0.5507979025745755


### `np.isclose()`

In [80]:
np.float64(1 / 3) * 3 == 1

True

In [82]:
np.isclose(np.float64(1 / 3) * 3, 1)

True

---

# scipy.sparse

In [86]:
from scipy.sparse import csr_matrix
from sys import getsizeof

In [87]:
a = np.random.randint(0, 2, (1, 1_000_000))
print(getsizeof(a))

a_csr = csr_matrix(a)
print(getsizeof(a_csr))

4000112
56


In [88]:
a.mean()

0.499759

#### Или можно вот так вот создать:

In [89]:
values = list(range(1, 11))
row_idxs = [0, 1, 2, 0, 1, 2, 0, 1, 2, 3]
column_idxs = [4, 3, 2, 1, 1, 2, 3, 4, 0, 0]

csr_improvisation = csr_matrix((values, (row_idxs, column_idxs)))
csr_improvisation.toarray()

array([[ 0,  4,  0,  7,  1],
       [ 0,  5,  0,  2,  8],
       [ 9,  0,  9,  0,  0],
       [10,  0,  0,  0,  0]], dtype=int32)